travis:
  secure:
    BINSTAR_TOKEN: B8AjWRzNVgK3kvlYiYxuHUZYJlKTmT+QetNXQ6Q/SUtZOW45V6/5+UHtx8jqxCq1DWLqceUvfB0vpK+gmqcQeNZKeXdyXMjDuSclX8mevX01ZKmXe/MHU+9ysJfKaisSRMee/RRLQ40Yt1MDnKLmqWtlHMCmpDauEMRvIkQdci0YZfTgtA/wFgnKf/abg9jrvSzWQEXzuDjokaCzJ+aduD5J+mNAz9mss3GE+TtBdeD8tcTGbGvVPRl+KdGcuTPQZsvkB32mpx4/GYRSLXYNMeYwWZBNsJ+VaLvGFbrDXHPPaa7+R3vOsfP9b1abYlPYQnEkS/6h1cDgBriSKjPkOryiFht3WZcevpw7D6hBGXPmCgnOQleEbkcUwdDlODW/Kk650DAZ0IM2F9ZuCCSFaLH01Hnta4o0f35lGOKsrAkR5l/z3QChZem492wzr/Gs+5FfEwWvqEFI4juHFFk+4ixfa8s4+AXrawSpQdZb28aaR2ue6CZPwfnCTlT6TrmthgIQ1i1O5Q5+k+uqdRPqI4CRpQsfdhgQ7XQsVS58u/binPuQmvWOqfJH1uiyBYwZgjlp8IZPcUSuWdSKge4N+I0MDVE4etTx5JBd/5lP5fLwaQOlc8v1xhPw+fsHV2hoR8OXwMoZN8m0COwWPsh2gYMQIH5sBjrwnTWkJLhIPFc=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
