travis:
  secure:
    BINSTAR_TOKEN: q1AG8kORf+rRQ+Kt54Ttr5BPvA4cycgkY7AiR0mgeQ/kVVmcB/ZNAXJ2VV+25CG072NBveUq6/zGCitMeCF4UfbIODX9Q5woN5gKFx4ZZWWo1XVvng9bs1o6WZSE1K8THxq7xt4ZZCb2yQaIbsZU8PrrcyOLKMMXTYn2iO7gDxRboPdAMl+q5GY1LUZ34lp+ixy1FEhWjZV6cdBR5IhkHSpcAIrofzDmbuKyVZdkm0PA91jr2OLm3gZJN91xX6gaK2bWS2Jf9CdHYk+Uu3i8q1hlYy6mmsbswSHiM3TOmofTWRy1WNIcPW/2FO3OuY/VwDk5LnTppJqWnI1HVERP/S7UmUc0lNjkf15Cr4+vgnvNK7UTnDw/Jlx19bNkm8VEOaBr0kR3WrC+y1iiJi97Zx71VSn125p7P+wy3bbm5WY7qi5ceSPWO+0Z/R1XMr+JB4WxE6WdsFSFfP3GnHsoYztf7fZCiHX4ZWl5ILpj6zSz4Fod6TZnOjjjr+q614QtUFLurywJW0CvrSafpteQVg2F69w+X8Xz1xqZxr5db5u/aTbmqMEJPVRxvf7cxC585VHuZbTcXwdtBsvcVnBmaOZJ2JTq6opRrGvvSo5aoL0QXwN1mrl1fo0fshW3YqjnNKZGglQku7xLZlTLgmCswa1zberYa2fx6p2fJIxN/VU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
