travis:
  secure:
    BINSTAR_TOKEN: lKmoLTEq3dW2iYsDgv0Xxm3iTt1LUwzS1a4OS3HvH7iFaz19nFwEW/wr2upv9+Y+y8o43w2VEjlKUaXAdjLCibaNUq5Jm4CkB44p1xVF+JMhhom649zFzbSknRY/2p7f1hDvClLnsjuiIFXvZT6AkbFCVgt3TRvMQvqZ2NeQAeBH/eHvxTc5wga/q6Qc/jPjzuh8aqaU6i/NP2divFNc5iJfqzUFqXcRpnXv2mAvq+ryJ/vrdk+kZJMrdnBy3qWjxxAsYdAuGn00Uf71jfhz31tCoq4SAIHfSl5BSURbbtd/dQ1kLcWSO/JpmebNSPBKtap02o1w2VbNq0Wwb9sgQV6ZHX17WfDukAMLxDD7OV5LMM0sPh51xySzXzUgRxJ7I9XqEDDuLnelhy+XyeRokdUPin8Ls+BeSXtYpi0JRo+iauW5DjRyZtnJ9TekO5+/RfBANMb0mK2sKYstf56iE3dIhMfXbeTguc3hmrEQheCsbIRbbbkr0jaB2PHqh8xxjikqjazGJGyx8T/V0wnMAEkbHQWNXTTqNT9tXhmA8z1DoV9yDTRa9kM3IWC61qDp+z/vSC0VdYMI+bRuNVm6+NXjs4pUbMVv9cGYAAerNM35eY6ny7zoLaw4oMwDhAnNwy28CEyQAuTiGMC5wj/AW1du1ORR0+y5Q/+dWiG9Rs4=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
