appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: lojCLSlSmZ35ZuA+j68pxDKpeIcnRDaTN+byHDqkTCyyOotEBRGMDBNZuREntkOeXSR9d42SonL4GjZaxh5uX0gp5acFyc+8tYENjeXUmkDlgOQv+pS7bmIQ8U5J6g2IMhKYmQiVxbeuK9BywL6cbgRiDZjRmsoWYQ4h+vlSl+MXhYasJjdWPn4O+n5Ts14uPTyIefWVx347Xd2nvy2JRzwIUqmHk/IhU/gZTnRDJaAKtlHfhh1XrONF6NVZxxBeDspxthaGHflZq/4FUPoTx8BAL7k7P/cKq7PPFzZFpan9INzGMTTbHswWpLoxmcJNE7FOrEw4/mCBbVyFozqMvo+hR7/i0gvlt4P6ykWVbeDsgKx6hs9WVAvYYwc8Ka134KJZ1i3iSvBpZ4oof4RNwIsyE0FNSHFEDeADT6aJpTnLwxDoLtjUEJvwJpGlE04OcTP9fGCDDR+5x3RiNI27fsZEi47pVkdaKZ8AvHdcifLfjc29RMOd5sp66mQKyDz0z7w+C1wEnTHJetD35rFVA+UyCFk6RIvMK8z+PsWb1TH0M5Fk14KitQGXfNVFgurKz5iM8KkkYejRm4hjB6qBplrHRMBpjgugmQbtw+cD+Tek1DCpfJhQD4SJosfL2Hm0uUEi/cNPXW53Zxmf3kYe9FSSyRF/YOLmT8tj0shuN0c=}
