travis:
  secure:
    BINSTAR_TOKEN: ERujAA46yhTO+JksuJH4yCqTH7B8dguaAIj18c39jVDoFiKVspgO22vgvfqY/bi/CN1mgsByIe4g52JIitDrvIns4n3pM4k+PqlR1PSH2SJAF01j/PzlxWJrfVX1t8CHarfW4WQhtRkwACotb8ALJcrp6NBM8fiepHJftjTTYZG1djtfjOxyR2io5avB/JsifUA6l5lyNTq1wvgo9slbmUnoMGJq2YH0YyYT5NIAhpf+u7ZX1hTKk6s06/K0vpAb3sl5VpPsziC411hJa8x5YykoBfKDgpNAJCY3wpdbvbllsMzHffdeZw0wHRAPeNLCwpM6REsFLS7UhumyN4PoBmwfazt7T5NUD+6CUivqToc5dx1aBFsp3WXRHZq16MMFSjL1MlGRK7QUCMnzAW8+Sh/xtPHRt7vOohvIJIOu7IiZEg9oWo4autQCjE7V7TELmCSBqBwbJrkZNkJ10YTOJMWrCZWAY7mLOZE3e6mchCHQKPYfDOppYUmXwdR7zO0lPOYssoiIlhoSeEa3pzuS/Kq1H/GlWTFEqskQ8hrOCX5t0f7TQV4rSjkvm+wCR6u6lS+dYCvm4gdJ0UKE6+4xgZZ+DhEeeuhB+hQwtDS/n5SKqLKs6MIwDuyYNJyKoNbSQ/zR+Xl5KRr3IrVaC571xy4SatT4Dn9N1ly8YCLcjZ8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
