travis:
  secure:
    BINSTAR_TOKEN: S9gFmkAA3b9vLz92S8wB44EFPQQ4AWY5FLVfjFOk8AyEw+S81I2do+vdgS1ia4wBm4fKSZTLIamC9s5ZF/umQPEbFNY7LMt3ILEQISzyT2CyHzVYnqiOEt80Ei8Gcd3wLPXsfeS33U1HsYxes03u9CrJezoX9IIK4fqsrzbl39rWodBshIypJveSvukosoKYzKUZ/r7G1cYQi/mu7Saq8Gwp53dx8PXS5njL9u2LFpvSZY+bOUcIXNaWCg/1RTURg1GXrPNHE76lXV6hayiPgaAR2CG0FcXzFS3Azm978ulWn5FHy7u4PWPGEcMTcB/DJhJ1m7ZA85h15KaDsxC8XF7q1dJ4dveVCZxgLfaDoInar9rbeZT499YafBJYwjiv839ruV7Ix7uHYn12sufPFEHO/dp3nmh8ovLqmLBSD97vhAYcZeY/3I92KEJxQ7k2PmdYNd05D2LadmaPm5zZBsc6O775rHb3tAda6wiLPweUL5B28gglEI1UJoUXMNDJm4rDyG20vxll46QjI3DXVEXFB/nJDg89A8RvsqXQBe5/HEySP/ngpYPmoLRQ6CWapseVvRg35MvsN6v1LPtvIdShhi9KLbfiaUuijc0nVIiaRQlPfcuUB5oyQKBbEPDiJCF+iGGZ3MRorvJ+xXLzG76zIRrC7GIJAZ4MsUcgwzE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
